name: Integration

on:
  push:
    branches:
      - main
      - integration-test/**

jobs:
  tests:
    name: integration tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      
      - name: Run only if its a commit to main
        if: github.ref == 'refs/heads/main'
        run: 'echo The Ref is: ${{ github.ref }}'
        
      - name: Try to fail
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('this thing failed')

      - run: 'echo Integration tests are done!'
      
      - name: Report main failures to slack
        uses: jobs.slack-notify
        if: always() && github.ref == 'refs/heads/main'

      # - name: Report main failures to slack
      #   uses: ravsamhq/notify-slack-action@v2
      #   if: always() && github.ref == 'refs/heads/main'
      #   with:
      #     status: ${{ job.status }}
      #     notification_title: "THIS RAN ON MAIN!!! - {workflow} has {status_message}"
      #     notify_when: "failure"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: Report anything but main failures to slack
      #   uses: ravsamhq/notify-slack-action@v2
      #   if: always() && github.ref != 'refs/heads/main'
      #   with:
      #     status: ${{ job.status }}
      #     notification_title: "THIS DID NOT RUN ON MAIN!!! - {workflow} has {status_message}"
      #     notify_when: "failure"
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NOT_MAIN }}

  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Report anything but main failures to slack
        uses: ravsamhq/notify-slack-action@v2
        if: always() && github.ref != 'refs/heads/main'
        with:
          status: ${{ job.status }}
          notification_title: "THIS DID NOT RUN ON MAIN!!! - {workflow} has {status_message}"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NOT_MAIN }}